# Generated by Django 2.0 on 2018-05-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('descript', models.TextField(blank=True, null=True)),
                ('download_permission', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
