# Generated by Django 2.0 on 2018-06-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_text', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='is_delete',
            new_name='invisible',
        ),
    ]
